#!/bin/sh
# Installs each database's authorization capability key from AUTHZ_CAPABILITY_KEYS
# (generated by setup.sh) into authz.context_keys, as that database's migrator
# switched to the owner role. Idempotent: an existing key ID is left untouched.
set -eu
: "${PGHOST:?PGHOST is required}"
: "${AUTHZ_CAPABILITY_KEYS:?AUTHZ_CAPABILITY_KEYS is required}"
install_key() {
  database="$1"; role_prefix="$2"; password_variable="$3"
  eval "password=\${$password_variable:?$password_variable is required}"
  entry="$(printf '%s' "$AUTHZ_CAPABILITY_KEYS" | tr '{' '\n' | grep "\"audience\":\"${database}\"")"
  key_id="$(printf '%s' "$entry" | sed -E 's/.*"key_id":"([^"]+)".*/\1/')"
  secret="$(printf '%s' "$entry" | sed -E 's/.*"secret_base64":"([^"]+)".*/\1/')"
  echo "installing capability key for ${database}"
  PGPASSWORD="$password" psql --quiet --set=ON_ERROR_STOP=1 \
    --host="$PGHOST" --username="aether_${role_prefix}_migrator" --dbname="$database" \
    --set=key_id="$key_id" --set=audience="$database" --set=secret="$secret" \
    --set=owner="aether_${role_prefix}_owner" <<'SQL'
SET ROLE :"owner";
INSERT INTO authz.context_keys (key_id, audience, key_material, not_before, not_after)
VALUES (:'key_id'::uuid, :'audience', decode(:'secret', 'base64'), clock_timestamp() - interval '1 minute',
        clock_timestamp() + interval '825 days')
ON CONFLICT (key_id) DO NOTHING;
SQL
}
install_key aether_identity     identity      IDENTITY_DB_PASSWORD
install_key aether_tenant       tenant        TENANT_DB_PASSWORD
install_key aether_users        user          USERS_DB_PASSWORD
install_key aether_qbank        question_bank QBANK_DB_PASSWORD
install_key aether_assessment   assessment    ASSESSMENT_DB_PASSWORD
install_key aether_submission   submission    SUBMISSION_DB_PASSWORD
install_key aether_seb          seb           SEB_DB_PASSWORD
install_key aether_notification notification  NOTIFICATION_DB_PASSWORD
install_key aether_analytics    analytics     ANALYTICS_DB_PASSWORD
echo "all capability keys installed"
