#!/usr/bin/env bash
# One-time secret and certificate generation for the single-server stack.
#   .env         database/MinIO passwords, identity signing keys, KMS key,
#                per-database authorization capability keys, Judge0 API token
#   judge0.conf  Judge0's own settings and passwords
#   certs/  a private CA and one certificate per service (server + client):
#           DNS SAN and CN = service name, URI SAN spiffe://aethercode.local/<service>
# It refuses to overwrite existing secrets so they are never rotated by accident.
set -euo pipefail
cd "$(dirname "$0")"
if [[ -e .env || -e certs || -e judge0.conf ]]; then
  echo ".env, judge0.conf or certs/ already exists; remove them deliberately to regenerate" >&2
  exit 1
fi
umask 077
readonly SERVICES=(gateway identity tenant user question-bank assessment submission judge seb notification analytics)
readonly AUDIENCES=(aether_identity aether_tenant aether_users aether_qbank aether_assessment aether_submission aether_seb aether_notification aether_analytics)

hex() { openssl rand -hex 24; }
b64() { openssl rand -base64 "$1" | tr -d '\n'; }
uuid() { cat /proc/sys/kernel/random/uuid; }

# Identity assertion key: Ed25519 seed (32 bytes) and its public key, both base64.
key_der="$(mktemp)"
openssl genpkey -algorithm ed25519 -outform DER -out "$key_der"
identity_seed="$(tail -c 32 "$key_der" | base64 -w0)"
identity_public="$(openssl pkey -inform DER -in "$key_der" -pubout -outform DER | tail -c 32 | base64 -w0)"
rm -f "$key_der"
identity_key_id="$(uuid)"

# One capability key per database audience; the provision job installs them.
keyring="["
for audience in "${AUDIENCES[@]}"; do
  keyring+="{\"audience\":\"${audience}\",\"key_id\":\"$(uuid)\",\"secret_base64\":\"$(b64 32)\"},"
done
keyring="${keyring%,}]"

judge0_token="$(hex)"

{
  echo "# Generated by setup.sh on $(date -u +%FT%TZ). Keep private; never commit."
  echo "POSTGRES_SUPERUSER_PASSWORD=$(hex)"
  for name in IDENTITY TENANT USERS QBANK ASSESSMENT SUBMISSION SEB NOTIFICATION ANALYTICS; do
    echo "${name}_DB_PASSWORD=$(hex)"
  done
  echo "JUDGE_DB_PASSWORD=$(hex)"
  echo "JUDGE_RABBITMQ_PASSWORD=$(hex)"
  echo "JUDGE0_AUTH_TOKEN=${judge0_token}"
  echo "MINIO_ROOT_USER=aethercode"
  echo "MINIO_ROOT_PASSWORD=$(hex)"
  echo "IDENTITY_ACCESS_TOKEN_KEY_ID=${identity_key_id}"
  echo "IDENTITY_ACCESS_TOKEN_PRIVATE_KEY_BASE64=${identity_seed}"
  echo "IDENTITY_ASSERTION_PUBLIC_KEYS={\"${identity_key_id}\":\"${identity_public}\"}"
  echo "IDENTITY_DELIVERY_TOKEN_HMAC_KEY_BASE64=$(b64 32)"
  echo "IDENTITY_MFA_KEY_REFERENCE=local-mfa-1"
  echo "IDENTITY_MFA_MASTER_KEYS_JSON={\"local-mfa-1\":\"$(b64 32)\"}"
  # One local KMS key for every service that encrypts or decrypts platform
  # objects (stand-in for a single managed KMS).
  echo "PLATFORM_KMS_LOCAL_KEY=$(b64 32)"
  # Encrypts .seb launch files and is Safe Exam Browser's quit password.
  echo "SEB_LAUNCH_PASSWORD=$(hex)"
  echo "AUTHZ_CAPABILITY_KEYS=${keyring}"
} > .env

# Judge0 reads this file directly; limits match the exam app's tuned values.
cat > judge0.conf <<CONF
COUNT=16
MAX_QUEUE_SIZE=5000
MAX_CPU_TIME_LIMIT=120
MAX_WALL_TIME_LIMIT=240
MAX_MAX_FILE_SIZE=8192
MAX_MEMORY_LIMIT=512000
MAX_PROCESSES_AND_OR_THREADS=128
ENABLE_NETWORK=false
ENABLE_CALLBACKS=false
ENABLE_BATCHED_SUBMISSIONS=true
ENABLE_WAIT_RESULT=false
AUTHN_HEADER=X-Auth-Token
AUTHN_TOKEN=${judge0_token}
REDIS_HOST=judge0-redis
REDIS_PORT=6379
REDIS_PASSWORD=$(hex)
POSTGRES_HOST=judge0-db
POSTGRES_PORT=5432
POSTGRES_DB=judge0
POSTGRES_USER=judge0
POSTGRES_PASSWORD=$(hex)
CONF
chmod 0644 judge0.conf

# Private CA and per-service certificates (ECDSA P-256, TLS 1.3 capable).
mkdir -p certs
openssl req -x509 -newkey ec -pkeyopt ec_paramgen_curve:P-256 -nodes -days 1825 \
  -subj "/CN=AetherCode single-server CA" -keyout certs/ca.key -out certs/ca.crt 2>/dev/null
for service in "${SERVICES[@]}"; do
  openssl req -newkey ec -pkeyopt ec_paramgen_curve:P-256 -nodes -subj "/CN=${service}" \
    -keyout "certs/${service}.key" -out "certs/${service}.csr" 2>/dev/null
  openssl x509 -req -in "certs/${service}.csr" -CA certs/ca.crt -CAkey certs/ca.key -CAcreateserial \
    -days 825 -out "certs/${service}.crt" -extfile <(printf '%s\n' \
      "subjectAltName=DNS:${service},URI:spiffe://aethercode.local/${service}" \
      "extendedKeyUsage=serverAuth,clientAuth" \
      "keyUsage=digitalSignature") 2>/dev/null
  rm -f "certs/${service}.csr"
done
# Services run as a non-root user and must read their own key.
chmod 0755 certs
chmod 0644 certs/*.crt certs/*.key
rm -f certs/ca.key certs/ca.srl
echo "wrote $(pwd)/.env, $(pwd)/judge0.conf and $(pwd)/certs/"
