#!/usr/bin/env bash
# Creates deploy/single-server/.env with fresh random secrets. Run once per
# server; it refuses to overwrite an existing .env so secrets are never rotated
# by accident.
set -euo pipefail
cd "$(dirname "$0")"
if [[ -e .env ]]; then
  echo ".env already exists; delete it deliberately to regenerate secrets" >&2
  exit 1
fi
secret() { openssl rand -hex 24; }
umask 077
{
  echo "# Generated by setup.sh on $(date -u +%FT%TZ). Keep private; never commit."
  echo "POSTGRES_SUPERUSER_PASSWORD=$(secret)"
  for name in IDENTITY TENANT USERS QBANK ASSESSMENT SUBMISSION SEB NOTIFICATION ANALYTICS; do
    echo "${name}_DB_PASSWORD=$(secret)"
  done
  echo "MINIO_ROOT_USER=aethercode"
  echo "MINIO_ROOT_PASSWORD=$(secret)"
} > .env
echo "wrote $(pwd)/.env"
